import type { CompanyArchive } from '@/lib/types'

export const archiveSeed: CompanyArchive[] = [
  {
    id: '1',
    title: 'Laporan Keberlanjutan 2025',
    slug: 'laporan-keberlanjutan-2025',
    description: 'Laporan Keberlanjutan (Sustainability Report) PT Gadai Sakti Indonesia tahun 2025 mengenai komitmen tata kelola perusahaan, tanggung jawab sosial, dan pelestarian lingkungan.',
    year: 2025,
    documentType: 'Laporan Keberlanjutan',
    fileUrl: '/archives/laporan-keberlanjutan-2025.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
  {
    id: '2',
    title: 'Laporan Keberlanjutan Tahun 2025 Banten',
    slug: 'laporan-keberlanjutan-2025-banten',
    description: 'Laporan Keberlanjutan operasional, tata kelola, dan kontribusi sosial kemasyarakatan PT Gadai Sakti wilayah Banten tahun 2025.',
    year: 2025,
    documentType: 'Laporan Keberlanjutan',
    fileUrl: '/archives/laporan-keberlanjutan-2025-banten.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
  {
    id: '3',
    title: 'Laporan Keuangan Audited Gadai Jakarta 2025',
    slug: 'laporan-keuangan-audited-gadai-jakarta-2025',
    description: 'Laporan Keuangan Audited PT Gadai Sakti wilayah DKI Jakarta untuk tahun buku yang berakhir pada 31 Desember 2025 yang telah diaudit oleh Kantor Akuntan Publik.',
    year: 2025,
    documentType: 'Laporan Keuangan',
    fileUrl: '/archives/laporan-keuangan-audited-gadai-jakarta-2025.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
  {
    id: '4',
    title: 'Laporan Keuangan Audited Gadai Banten 2025',
    slug: 'laporan-keuangan-audited-gadai-banten-2025',
    description: 'Laporan Keuangan Audited PT Gadai Sakti wilayah Banten untuk tahun buku yang berakhir pada 31 Desember 2025 yang telah diaudit oleh Kantor Akuntan Publik.',
    year: 2025,
    documentType: 'Laporan Keuangan',
    fileUrl: '/archives/laporan-keuangan-audited-gadai-banten-2025.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
  {
    id: '5',
    title: 'Laporan Keuangan Audited Gadai DIY 2025',
    slug: 'laporan-keuangan-audited-gadai-diy-2025',
    description: 'Laporan Keuangan Audited PT Gadai Sakti wilayah D.I. Yogyakarta untuk tahun buku yang berakhir pada 31 Desember 2025 yang telah diaudit oleh Kantor Akuntan Publik.',
    year: 2025,
    documentType: 'Laporan Keuangan',
    fileUrl: '/archives/laporan-keuangan-audited-gadai-diy-2025.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
  {
    id: '6',
    title: 'Laporan Keuangan Audited Gadai Nusantara 2025',
    slug: 'laporan-keuangan-audited-gadai-nusantara-2025',
    description: 'Laporan Keuangan Audited PT Gadai Sakti Nusantara untuk tahun buku yang berakhir pada 31 Desember 2025 yang telah diaudit oleh Kantor Akuntan Publik.',
    year: 2025,
    documentType: 'Laporan Keuangan',
    fileUrl: '/archives/laporan-keuangan-audited-gadai-nusantara-2025.pdf',
    coverImage: '',
    publishedAt: new Date('2025-12-31T00:00:00.000Z'),
  },
]
