import type { Article } from '@/lib/types'

export const articleSeed: Article[] = [
  {
    id: '1',
    title: '5 Tanda Kamu Perlu Mengambil Langkah Sakti ke Gadai Terdekat',
    slug: '5-tanda-kamu-perlu-mengambil-langkah-sakti-ke-gadai-terdekat',
    description: 'Kebutuhan dana mendadak bisa datang kapan saja. Kenali situasi ketika gadai dapat menjadi alternatif dana yang cepat dan terukur.',
    content: `## Gadai terdekat bisa jadi langkah yang lebih aman\nSaat kebutuhan dana muncul, keputusan yang baik dimulai dari memahami nilai barang, biaya, jangka waktu, dan kemampuan pelunasan. Gadai dapat menjadi alternatif ketika Anda membutuhkan dana tanpa menjual barang yang masih ingin dimiliki.\n\n## Kendaraan rusak dan perlu segera diperbaiki\nPerbaikan kendaraan sering tidak bisa ditunda karena berkaitan dengan mobilitas harian. Barang elektronik atau kendaraan lain yang memenuhi kriteria dapat digunakan sebagai jaminan sesuai hasil taksiran.\n\n## Renovasi rumah yang tidak bisa menunggu\nKebutuhan rumah tangga tertentu membutuhkan dana dalam waktu singkat. Pilih nominal pinjaman yang realistis dan pastikan memahami tanggal jatuh tempo sebelum menyetujui transaksi.\n\n## Biaya pengobatan atau kebutuhan keluarga\nUtamakan kejelasan biaya dan proses. Gadai Sakti menjelaskan nilai taksiran dan biaya sebelum transaksi dilanjutkan agar keputusan dapat dibuat dengan informasi yang cukup.\n\n## Biaya pendidikan\nDana pendidikan dapat muncul di waktu yang berdekatan dengan kebutuhan lain. Gunakan simulasi untuk mendapatkan gambaran awal sebelum datang ke cabang.\n\n## Kebutuhan usaha dan arus kas\nUntuk kebutuhan produktif, sesuaikan nominal dengan rencana pembayaran agar barang dapat ditebus sesuai target.`,
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-04-29'),
    category: 'Tips Keuangan',
    readTime: 6,
  },
  {
    id: '2',
    title: 'Panduan Gadai Laptop agar Taksiran Tetap Optimal',
    slug: 'panduan-gadai-laptop-taksiran-optimal',
    description: 'Persiapkan laptop, aksesori, dan informasi perangkat sebelum datang ke cabang agar proses penaksiran lebih lancar.',
    content: `## Persiapkan perangkat dengan baik\nPastikan laptop dapat dinyalakan, layar berfungsi, dan kondisi fisik dapat diperiksa dengan mudah.\n\n## Bawa aksesori yang relevan\nAdaptor dan aksesori utama membantu petugas memeriksa perangkat dengan lebih lengkap.\n\n## Cadangkan data pribadi\nLakukan pencadangan data penting dan keluar dari akun pribadi sebelum menyerahkan perangkat untuk proses pemeriksaan.`,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-04-22'),
    category: 'Tips Gadai',
    readTime: 5,
  },
  {
    id: '3',
    title: 'Cara Menentukan Cabang Gadai Terdekat dari Lokasi Kamu',
    slug: 'cara-menentukan-cabang-gadai-terdekat',
    description: 'Gunakan halaman lokasi cabang untuk mencari outlet terdekat dan membuka rute perjalanan langsung di Google Maps.',
    content: `## Cari berdasarkan wilayah\nMasukkan kota atau nama cabang pada halaman Lokasi Cabang untuk mempersempit hasil pencarian.\n\n## Gunakan lokasi perangkat\nJika izin lokasi diberikan, sistem dapat membantu mengurutkan cabang berdasarkan jarak garis lurus dari posisi pengguna.\n\n## Buka rute perjalanan\nTombol detail lokasi membuka Google Maps dengan tujuan cabang sehingga rute, jarak jalan, dan estimasi waktu dapat dihitung oleh Google Maps.`,
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-04-15'),
    category: 'Informasi Cabang',
    readTime: 4,
  },
  {
    id: '4',
    title: 'Sebelum Gadai Handphone, Cek 5 Hal Ini',
    slug: 'sebelum-gadai-handphone-cek-5-hal',
    description: 'Kondisi fisik, fungsi perangkat, kelengkapan, kapasitas, dan tahun perangkat dapat memengaruhi hasil pemeriksaan.',
    content: `## Kondisi fisik\nBersihkan perangkat agar kondisi bodi dan layar mudah diperiksa.\n\n## Fungsi dasar\nPastikan layar sentuh, kamera, speaker, tombol, dan pengisian daya dapat diuji.\n\n## Informasi perangkat\nModel, kapasitas penyimpanan, dan tahun perangkat membantu mempercepat identifikasi barang.`,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-04-08'),
    category: 'Tips Gadai',
    readTime: 4,
  },
  {
    id: '5',
    title: 'Memahami Taksiran Barang Elektronik secara Sederhana',
    slug: 'memahami-taksiran-barang-elektronik',
    description: 'Nilai taksiran bukan hanya melihat harga beli. Kondisi, spesifikasi, umur, dan nilai pasar ikut diperhitungkan.',
    content: `## Kondisi barang\nBarang dengan fungsi lengkap dan kondisi terawat umumnya lebih mudah dinilai.\n\n## Spesifikasi dan umur\nModel, kapasitas, generasi, dan tahun rilis membantu menentukan posisi perangkat di pasar.\n\n## Nilai pasar\nPenaksiran mempertimbangkan nilai pasar yang relevan pada saat pemeriksaan dilakukan.`,
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-03-30'),
    category: 'Edukasi',
    readTime: 5,
  },
  {
    id: '6',
    title: 'Gadai Motor: Dokumen dan Persiapan Sebelum ke Cabang',
    slug: 'gadai-motor-dokumen-dan-persiapan',
    description: 'Pelajari persiapan awal agar proses pemeriksaan kendaraan dan dokumen berjalan lebih efisien di cabang.',
    content: `## Siapkan identitas\nBawa identitas sesuai ketentuan yang berlaku di cabang.\n\n## Siapkan kendaraan dan dokumen\nPastikan kendaraan dapat diperiksa dan dokumen yang disyaratkan tersedia.\n\n## Konfirmasi cabang\nHubungi cabang tujuan sebelum datang bila Anda ingin memastikan jam layanan atau kebutuhan dokumen.`,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-03-20'),
    category: 'Produk',
    readTime: 5,
  },
  {
    id: '7',
    title: 'Kenapa Simulasi Gadai Sebaiknya Dilakukan Lebih Dulu?',
    slug: 'kenapa-simulasi-gadai-dilakukan-lebih-dulu',
    description: 'Simulasi membantu memberi gambaran awal sebelum pemeriksaan fisik dan taksiran final dilakukan di cabang.',
    content: `## Gambaran awal\nSimulasi membantu Anda memahami rentang nilai sebelum datang ke cabang.\n\n## Persiapan keputusan\nAnda dapat membandingkan kebutuhan dana dengan estimasi yang tersedia.\n\n## Taksiran final tetap di cabang\nNilai akhir ditentukan setelah barang diperiksa langsung oleh petugas.`,
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-03-12'),
    category: 'Edukasi',
    readTime: 4,
  },
  {
    id: '8',
    title: 'Tips Menjaga Barang Elektronik Sebelum dan Setelah Digadai',
    slug: 'tips-menjaga-barang-elektronik',
    description: 'Perawatan sederhana membantu mempertahankan kondisi perangkat dan memudahkan pemeriksaan saat proses gadai.',
    content: `## Gunakan pelindung\nCasing dan pelindung layar dapat membantu mengurangi kerusakan fisik.\n\n## Hindari kelembapan\nSimpan perangkat di lokasi yang kering dan aman.\n\n## Simpan bukti transaksi\nPastikan dokumen transaksi disimpan hingga barang ditebus dan proses selesai.`,
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-03-05'),
    category: 'Tips Gadai',
    readTime: 4,
  },
  {
    id: '9',
    title: 'Pertanyaan yang Perlu Ditanyakan Sebelum Menyetujui Gadai',
    slug: 'pertanyaan-sebelum-menyetujui-gadai',
    description: 'Pastikan Anda memahami taksiran, biaya, jatuh tempo, pelunasan, dan prosedur perpanjangan sebelum transaksi.',
    content: `## Berapa nilai taksiran?\nMinta penjelasan nilai yang ditawarkan setelah pemeriksaan barang.\n\n## Bagaimana biaya dihitung?\nPastikan komponen biaya disampaikan sebelum transaksi diteruskan.\n\n## Kapan jatuh tempo?\nCatat tanggal penting dan tanyakan mekanisme perpanjangan atau pelunasan.`,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200',
    author: 'Tim Gadai Sakti',
    publishedAt: new Date('2025-02-25'),
    category: 'Edukasi',
    readTime: 5,
  },
]
