services:
  app:
    build:
      context: .
      network: host
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
    networks:
      - ks_default

networks:
  ks_default:
    external: true
